"""jsat.mcp.tools — JSON Schema definitions for all 47 JSAT MCP tools."""
from __future__ import annotations

MCP_TOOLS: list[dict] = [
    # ── Category 1: Index (8) ──────────────────────────────────────────
    {"name": "index_repo", "description": "Build or refresh codebase index.",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"}, "branch": {"type": "string"},
         "force": {"type": "boolean"}, "incremental": {"type": "boolean"}}}},
    {"name": "get_function", "description": "Get details of a function by name or file:line.",
     "inputSchema": {"type": "object", "properties": {
         "name": {"type": "string"}, "file": {"type": "string"}, "line": {"type": "integer"}}}},
    {"name": "get_class", "description": "Get details of a class.",
     "inputSchema": {"type": "object", "properties": {
         "name": {"type": "string"}, "file": {"type": "string"}}}},
    {"name": "list_services", "description": "List all services in the indexed repo.",
     "inputSchema": {"type": "object", "properties": {"language": {"type": "string"}}}},
    {"name": "list_endpoints", "description": "List API endpoints.",
     "inputSchema": {"type": "object", "properties": {
         "service": {"type": "string"}, "method": {"type": "string"},
         "auth": {"type": "boolean"}}}},
    {"name": "list_tables", "description": "List database tables.",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "trace_call_chain", "description": "Trace call chain from entry to target.",
     "inputSchema": {"type": "object", "required": ["from", "to"],
                     "properties": {"from": {"type": "string"}, "to": {"type": "string"}}}},
    {"name": "get_data_flow", "description": "Trace how data flows through the system.",
     "inputSchema": {"type": "object", "properties": {"service": {"type": "string"}}}},
    # ── Category 2: Blast Radius (5) ─────────────────────────────────
    {"name": "blast_radius_file", "description": "Blast radius for a file.",
     "inputSchema": {"type": "object", "required": ["file"],
                     "properties": {"file": {"type": "string"}, "max_depth": {"type": "integer"}}}},
    {"name": "blast_radius_diff", "description": "Blast radius from a git diff.",
     "inputSchema": {"type": "object", "required": ["diff"],
                     "properties": {"diff": {"type": "string"}, "max_depth": {"type": "integer"}}}},
    {"name": "blast_radius_symbol", "description": "Blast radius for a symbol.",
     "inputSchema": {"type": "object", "required": ["symbol"],
                     "properties": {"symbol": {"type": "string"}}}},
    {"name": "blast_radius_topic", "description": "Blast radius of a Kafka topic change.",
     "inputSchema": {"type": "object", "required": ["topic"],
                     "properties": {"topic": {"type": "string"}}}},
    {"name": "get_consumers", "description": "List consumers of an endpoint or topic.",
     "inputSchema": {"type": "object", "required": ["target"],
                     "properties": {"target": {"type": "string"}}}},
    # ── Category 3: Tests (6) ────────────────────────────────────────
    {"name": "get_test_gaps", "description": "Find uncovered code paths.",
     "inputSchema": {"type": "object", "properties": {
         "service": {"type": "string"}, "path": {"type": "string"}, "type": {"type": "string"}}}},
    {"name": "get_behavioral_coverage", "description": "Map behaviors to test coverage.",
     "inputSchema": {"type": "object", "properties": {"service": {"type": "string"}}}},
    {"name": "list_untested_paths", "description": "Top-N highest-risk untested paths.",
     "inputSchema": {"type": "object", "properties": {"limit": {"type": "integer"}}}},
    {"name": "generate_unit_test", "description": "Generate unit test for a function.",
     "inputSchema": {"type": "object", "required": ["function"],
                     "properties": {"function": {"type": "string"}}}},
    {"name": "generate_integration_test", "description": "Generate integration test.",
     "inputSchema": {"type": "object", "required": ["endpoint"],
                     "properties": {"endpoint": {"type": "string"}}}},
    {"name": "generate_contract_test", "description": "Generate contract test between services.",
     "inputSchema": {"type": "object", "required": ["producer", "consumer"],
                     "properties": {"producer": {"type": "string"},
                                    "consumer": {"type": "string"}}}},
    # ── Category 4: Security (5) ─────────────────────────────────────
    {"name": "security_scan_file", "description": "OWASP scan a file.",
     "inputSchema": {"type": "object", "required": ["file"],
                     "properties": {"file": {"type": "string"}, "severity": {"type": "string"}}}},
    {"name": "get_auth_coverage", "description": "Endpoints missing auth middleware.",
     "inputSchema": {"type": "object", "properties": {"service": {"type": "string"}}}},
    {"name": "list_secrets", "description": "Find hardcoded secrets (keys only, values redacted).",
     "inputSchema": {"type": "object", "properties": {"path": {"type": "string"}}}},
    {"name": "get_dependency_cves", "description": "CVEs in dependencies.",
     "inputSchema": {"type": "object", "properties": {"cvss_min": {"type": "number"}}}},
    {"name": "trace_data_flow", "description": "Trace user input for injection risks.",
     "inputSchema": {"type": "object", "required": ["entry_point"],
                     "properties": {"entry_point": {"type": "string"}}}},
    # ── Category 5: API Contract (4) ─────────────────────────────────
    {"name": "get_api_diff", "description": "Diff OpenAPI/AsyncAPI specs between branches.",
     "inputSchema": {"type": "object", "properties": {
         "base": {"type": "string"}, "head": {"type": "string"}}}},
    {"name": "check_breaking_changes",
     "description": "Classify API changes as breaking/non-breaking.",
     "inputSchema": {"type": "object", "properties": {
         "base": {"type": "string"}, "head": {"type": "string"}}}},
    {"name": "get_consumers_of_endpoint", "description": "All callers of a specific endpoint.",
     "inputSchema": {"type": "object", "required": ["endpoint"],
                     "properties": {"endpoint": {"type": "string"}}}},
    {"name": "get_compat_score", "description": "0-100 backward compatibility score.",
     "inputSchema": {"type": "object", "properties": {
         "base": {"type": "string"}, "head": {"type": "string"}}}},
    # ── Category 6: Knowledge (5) ────────────────────────────────────
    {"name": "knowledge_query", "description": "Answer a question from the knowledge base.",
     "inputSchema": {"type": "object", "required": ["question"],
                     "properties": {"question": {"type": "string"},
                                    "service": {"type": "string"}}}},
    {"name": "knowledge_add", "description": "Add a note to the knowledge base.",
     "inputSchema": {"type": "object", "required": ["text"],
                     "properties": {"text": {"type": "string"}, "category": {"type": "string"}}}},
    {"name": "knowledge_search", "description": "Semantic search over knowledge base.",
     "inputSchema": {"type": "object", "required": ["query"],
                     "properties": {"query": {"type": "string"}, "limit": {"type": "integer"}}}},
    {"name": "knowledge_list", "description": "List knowledge base entries.",
     "inputSchema": {"type": "object", "properties": {"category": {"type": "string"}}}},
    {"name": "knowledge_flag_stale", "description": "Mark an entry as potentially outdated.",
     "inputSchema": {"type": "object", "required": ["entry_id"],
                     "properties": {"entry_id": {"type": "string"}}}},
    # ── Category 7: Incident (4) ─────────────────────────────────────
    {"name": "investigate_incident", "description": "Ranked root-cause hypotheses for an incident.",
     "inputSchema": {"type": "object", "required": ["description"],
                     "properties": {"description": {"type": "string"},
                                    "since": {"type": "string"}}}},
    {"name": "get_hypotheses", "description": "Get current ranked hypotheses.",
     "inputSchema": {"type": "object", "properties": {"limit": {"type": "integer"}}}},
    {"name": "get_recent_changes", "description": "Recent commits for affected services.",
     "inputSchema": {"type": "object", "properties": {
         "since": {"type": "string"},
         "services": {"type": "array", "items": {"type": "string"}}}}},
    {"name": "generate_runbook", "description": "Generate a runbook from hypothesis.",
     "inputSchema": {"type": "object", "required": ["hypothesis"],
                     "properties": {"hypothesis": {"type": "string"}}}},
    # ── Category 8: Migration (3) ────────────────────────────────────
    {"name": "validate_migration", "description": "Validate a migration file for safety.",
     "inputSchema": {"type": "object", "required": ["file"],
                     "properties": {"file": {"type": "string"}}}},
    {"name": "estimate_lock_duration", "description": "Estimate lock time for an operation.",
     "inputSchema": {"type": "object", "required": ["operation", "table"],
                     "properties": {"operation": {"type": "string"}, "table": {"type": "string"},
                                    "row_count": {"type": "integer"}}}},
    {"name": "suggest_zero_downtime", "description": "Zero-downtime migration plan.",
     "inputSchema": {"type": "object", "required": ["operation"],
                     "properties": {"operation": {"type": "string"}}}},
    # ── Category 9: Review (3) ───────────────────────────────────────
    {"name": "submit_for_review", "description": "Submit diff for multi-model review.",
     "inputSchema": {"type": "object", "properties": {
         "diff": {"type": "string"}, "base": {"type": "string"}, "head": {"type": "string"}}}},
    {"name": "get_review_findings", "description": "Get completed review findings.",
     "inputSchema": {"type": "object", "properties": {"min_confidence": {"type": "string"}}}},
    {"name": "get_high_confidence_bugs", "description": "Findings confirmed by ≥2 models.",
     "inputSchema": {"type": "object", "properties": {}}},
    # ── Category 10: Export (2) ──────────────────────────────────────
    {"name": "export_index", "description": "Export current index to .jsat.zip.",
     "inputSchema": {"type": "object", "required": ["output"],
                     "properties": {"output": {"type": "string"},
                                    "compress": {"type": "integer"}}}},
    {"name": "import_index", "description": "Import index from .jsat.zip.",
     "inputSchema": {"type": "object", "required": ["archive"],
                     "properties": {"archive": {"type": "string"}}}},
    # ── Category 11: Meta (2) ────────────────────────────────────────
    {"name": "get_index_status", "description": "Index node/edge counts and freshness.",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_jsat_version", "description": "JSAT version, schema version, provider.",
     "inputSchema": {"type": "object", "properties": {}}},
    # ── Category 12: IThinking (5) ───────────────────────────────────
    {"name": "ithinking_plan", "description": "Run phases 0-4 without executing.",
     "inputSchema": {"type": "object", "required": ["task"],
                     "properties": {"task": {"type": "string"}}}},
    {"name": "ithinking_execute", "description": "Execute a pre-approved plan.",
     "inputSchema": {"type": "object", "required": ["task"],
                     "properties": {"task": {"type": "string"}}}},
    {"name": "ithinking_reflect", "description": "Generate phase 6 reflection.",
     "inputSchema": {"type": "object", "required": ["task", "result"],
                     "properties": {"task": {"type": "string"}, "result": {"type": "string"}}}},
    {"name": "ithinking_token_estimate", "description": "Estimate tokens: local vs LLM.",
     "inputSchema": {"type": "object", "required": ["task"],
                     "properties": {"task": {"type": "string"}}}},
    {"name": "ithinking_audit_assumptions", "description": "Run phase 4 assumption checklist.",
     "inputSchema": {"type": "object", "required": ["subtask"],
                     "properties": {"subtask": {"type": "string"}}}},
]
